'use client';

import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { Header } from '@/components/layout/Header';
import { SiteFooter } from '@/components/layout/SiteFooter';
import { AIChatWidget } from '@/components/agent/ChatWidget';

const CONTENT = {
  es: {
    title: 'Términos de Uso',
    updated: 'Última actualización: septiembre de 2026',
    intro:
      'Al usar Chess Art & AI Academy aceptas estas condiciones. Somos una academia digital educativa que une ajedrez, arte e inteligencia artificial.',
    sections: [
      {
        h: '1. Objeto',
        p: 'Ofrecemos galerías visuales (combinaciones, arte, libros, cine, música), un visor PGN interactivo y un agente conversacional con fines educativos y culturales.',
      },
      {
        h: '2. Uso permitido',
        p: 'Puedes explorar, estudiar y compartir enlaces a nuestros contenidos citando la fuente. No está permitido el uso automatizado masivo (scraping) que degrade el servicio ni suplantar la identidad del proyecto.',
      },
      {
        h: '3. Agente IA',
        p: 'Las respuestas del agente son generadas por modelos de IA y pueden contener errores: verifica siempre las variantes críticas sobre el tablero. El agente es una ayuda didáctica, no un árbitro oficial.',
      },
      {
        h: '4. Propiedad intelectual',
        p: 'Las ilustraciones de la serie Top 100 pertenecen a su autor, Pablo Iglesias. Las fichas del catálogo citan su procedencia; las imágenes definitivas se incorporan con su licencia correspondiente. El código y los textos propios se comparten para uso educativo citando el proyecto.',
      },
      {
        h: '5. Disponibilidad',
        p: 'El servicio se ofrece "tal cual". Podemos actualizar, pausar o retirar contenidos para mejorar la plataforma.',
      },
      {
        h: '6. Contacto',
        p: 'Para permisos, colaboraciones o avisos de contenido escribe a chessaiagency@gmail.com o usa la página de contacto.',
      },
    ],
  },
  en: {
    title: 'Terms of Use',
    updated: 'Last updated: September 2026',
    intro:
      'By using Chess Art & AI Academy you accept these terms. We are a digital academy bringing together chess, art and artificial intelligence for education and culture.',
    sections: [
      {
        h: '1. Purpose',
        p: 'We offer visual galleries (combinations, art, books, cinema, music), an interactive PGN viewer and a conversational agent for educational and cultural purposes.',
      },
      {
        h: '2. Permitted use',
        p: 'You may explore, study and share links to our content citing the source. Mass automated use (scraping) that degrades the service and impersonation of the project are not allowed.',
      },
      {
        h: '3. AI agent',
        p: 'Agent answers are generated by AI models and may contain mistakes: always verify critical lines on the board. The agent is a teaching aid, not an official arbiter.',
      },
      {
        h: '4. Intellectual property',
        p: 'Top 100 series illustrations belong to their author, Pablo Iglesias. Catalogue entries cite their source; final images are added under their respective license. Our own code and texts may be reused for education citing the project.',
      },
      {
        h: '5. Availability',
        p: 'The service is provided "as is". We may update, pause or remove content to improve the platform.',
      },
      {
        h: '6. Contact',
        p: 'For permissions, collaborations or content notices write to chessaiagency@gmail.com or use the contact page.',
      },
    ],
  },
} as const;

export default function TerminosPage() {
  const [locale, setLocale] = useState<'es' | 'en'>('es');

  useEffect(() => {
    const handleLanguageChange = (e: CustomEvent<'es' | 'en'>) => {
      setLocale(e.detail);
    };
    window.addEventListener('toggle-language', handleLanguageChange as EventListener);
    return () => window.removeEventListener('toggle-language', handleLanguageChange as EventListener);
  }, []);

  const t = CONTENT[locale];

  return (
    <div className="min-h-screen bg-chess-bg">
      <Header />
      <main className="pt-20 lg:pt-24">
        <motion.article
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="max-w-3xl mx-auto px-6 sm:px-8 py-12"
        >
          <h1 className="font-display text-3xl md:text-4xl font-bold text-chess-text-primary mb-2">
            {t.title}
          </h1>
          <p className="text-sm text-chess-text-muted mb-8">{t.updated}</p>
          <p className="text-chess-text-secondary leading-relaxed mb-8">{t.intro}</p>
          <div className="space-y-6">
            {t.sections.map((s) => (
              <section key={s.h} className="glass p-5 sm:p-6">
                <h2 className="font-display text-lg font-semibold text-chess-gold mb-2">{s.h}</h2>
                <p className="text-chess-text-secondary leading-relaxed text-[15px]">{s.p}</p>
              </section>
            ))}
          </div>
        </motion.article>
      </main>
      <SiteFooter />
      <AIChatWidget locale={locale} />
    </div>
  );
}
